web:
    build: web
    volumes:
        - web:/code
    ports:
        - "5000:5000"
    links:
        - redis
    command: python app.py
redis:
    image: redis:2.8.19
    ports:
        - "6379:6379"
tests:
    build: .
    volumes:
        - web:/code
    ports:
        - "5000:5000"
    links:
        - redis
    command: sh run_tests.sh
